#!/usr/bin/env bash
# This script displays line containing the bash word, allowing you to easily get the PID of your Bash process
# You cannot use pgrep
# shellcheck disable=SC2009

./1-list_your_processes | grep "bash"
